
GET http://localhost:8080/api/customers


### post

POST http://localhost:8080/api/customers
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "address": "123 Main St"
}


###

PUT http://localhost:8080/api/customers/1
Content-Type: application/json

{
  "name": "John Doe Updated",
  "email": "john.doe.updated@example.com",
  "address": "456 Elm St"
}


###

DELETE http://localhost:8080/api/customers/1



